# The URL the site will be built for
base_url = "http://www.rust4sharp.com"
theme = "dinkleberg"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "visual-studio-dark"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = false

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = true

[extra]
# Put all your custom variables here
author="The Sharp Ninja"
blog_logo="og_image.png"
blog_title="Rust 4 C# Developers"
keywords = ["Rust", "C#"]
og_image = "og_image.png"
og_alt_image = "rust4sharp.com"
og_site_name = "Rust 4 C# Developers"

## i18n words
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_relative_posts = "Related Posts"
label_next = "Next"
label_previous = "Previous"
label_page = "Page"
label_of = "of"
label_minutes = "minutes"

## Sidebar automatic links
sidebar = [
    {name="Rust Resources", urls=[
        {name="Rust Language", url="https://www.rust-lang.org/"},
        {name="Rust Playground", url="https://play.rust-lang.org/"},
        {name="Rust on Discord", url="https://discord.gg/aVESxV8"},
        {name="Rust on Reddit", url="https://www.reddit.com/r/rust/"},
        {name="Awesome Rust", url="https://github.com/kud1ing/awesome-rust"},
    ]},
    {name = "Social Media", urls=[
        {name="Medium", url="https://medium.com/the-unpopular-opinions-of-a-senior-developer"},
        {name="Github", url="https://github.com/gatewayprogrammingschool/Rust-For-CSharp-Developers"},
    ]},
]